// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Article Categories documents
 */
interface ArticleCategoriesDocumentData {
	/**
	 * Title field in *Article Categories*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article_categories.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Article Categories*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article_categories.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Image field in *Article Categories*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article_categories.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Article Categories document from Prismic
 *
 * - **API ID**: `article_categories`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleCategoriesDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<ArticleCategoriesDocumentData>,
		'article_categories',
		Lang
	>;

/**
 * Item in *Case Study → Authors*
 */
export interface CaseStudyDocumentDataAuthorsItem {
	/**
	 * author field in *Case Study → Authors*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.authors[].author
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	author: prismic.ContentRelationshipField<'people'>;
}

type CaseStudyDocumentDataSlicesSlice = MediaEmbedSlice | RichTextSlice;

/**
 * Content for Case Study documents
 */
interface CaseStudyDocumentData {
	/**
	 * Company field in *Case Study*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.company
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	company: prismic.TitleField;

	/**
	 * Description field in *Case Study*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Image field in *Case Study*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Set featured image as background field in *Case Study*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: case_study.showbackground
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	showbackground: prismic.BooleanField;

	/**
	 * Authors field in *Case Study*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.authors[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	authors: prismic.GroupField<Simplify<CaseStudyDocumentDataAuthorsItem>>;

	/**
	 * Slice Zone field in *Case Study*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<CaseStudyDocumentDataSlicesSlice> /**
	 * Meta Title field in *Case Study*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: case_study.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Case Study*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: case_study.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Case Study*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Case Study document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<CaseStudyDocumentData>,
	'case_study',
	Lang
>;

/**
 * Content for Publication Categories documents
 */
interface CategoriesDocumentData {
	/**
	 * Title field in *Publication Categories*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: categories.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Publication Categories*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: categories.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Image field in *Publication Categories*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: categories.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Publication Categories document from Prismic
 *
 * - **API ID**: `categories`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoriesDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<CategoriesDocumentData>,
	'categories',
	Lang
>;

type HomepageDocumentDataSlicesSlice =
	| CaseStudiesSlice
	| StaffSlice
	| ShowcaseSlice
	| HeroSlice
	| RichTextSlice
	| TabsSlice
	| TestimonialsSlice
	| HorizontalGallerySlice
	| MediaEmbedSlice
	| ServicesSlice
	| LatestArticlesSlice
	| FullWidthImageSlice
	| MasonryGallerySlice
	| FootnotesSlice
	| FaqsSlice
	| FormSlice
	| DiscoverCategoriesSlice
	| DetailsCardSlice
	| CarouselSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomepageDocumentData>,
	'homepage',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| FullWidthImageSlice
	| ServicesSlice
	| CarouselSlice
	| MediaEmbedSlice
	| FaqsSlice
	| DetailsCardSlice
	| FormSlice
	| MasonryGallerySlice
	| HorizontalGallerySlice
	| TabsSlice
	| DiscoverCategoriesSlice
	| FootnotesSlice
	| TestimonialsSlice
	| StaffSlice
	| LatestArticlesSlice
	| CaseStudiesSlice
	| ShowcaseSlice
	| HeroSlice
	| RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Show meta image as background field in *Page*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: page.showbackground
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	showbackground: prismic.BooleanField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

type PeopleDocumentDataSlicesSlice = never;

/**
 * Item in *People → Contact Platform*
 */
export interface PeopleDocumentDataPlatformItem {
	/**
	 * Platform Name field in *People → Contact Platform*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: twitter
	 * - **API ID Path**: people.platform[].platform_name
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	platform_name: prismic.SelectField<'twitter' | 'instagram' | 'email', 'filled'>;

	/**
	 * Link field in *People → Contact Platform*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: people.platform[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Link Text field in *People → Contact Platform*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: people.platform[].link_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link_text: prismic.KeyTextField;
}

/**
 * Content for People documents
 */
interface PeopleDocumentData {
	/**
	 * Name field in *People*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: people.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * Email field in *People*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: people.email
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	email: prismic.KeyTextField;

	/**
	 * Work Title field in *People*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: people.work_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	work_title: prismic.KeyTextField;

	/**
	 * Biography field in *People*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: people.biography
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	biography: prismic.RichTextField;

	/**
	 * Image field in *People*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: people.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Set image as background field in *People*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: people.showbackground
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	showbackground: prismic.BooleanField;

	/**
	 * Slice Zone field in *People*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: people.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PeopleDocumentDataSlicesSlice> /**
	 * Contact Platform field in *People*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: people.platform[]
	 * - **Tab**: Contact Links
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */;
	platform: prismic.GroupField<Simplify<PeopleDocumentDataPlatformItem>>;
}

/**
 * People document from Prismic
 *
 * - **API ID**: `people`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PeopleDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PeopleDocumentData>,
	'people',
	Lang
>;

/**
 * Item in *Post → Authors*
 */
export interface PostDocumentDataAuthorsItem {
	/**
	 * Author field in *Post → Authors*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.authors[].author
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	author: prismic.ContentRelationshipField<'people'>;
}

/**
 * Item in *Post → Categories*
 */
export interface PostDocumentDataCategoriesItem {
	/**
	 * Category field in *Post → Categories*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.categories[].category
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	category: prismic.ContentRelationshipField<'article_categories'>;
}

type PostDocumentDataSlicesSlice =
	| CarouselSlice
	| MediaEmbedSlice
	| FaqsSlice
	| DetailsCardSlice
	| FootnotesSlice
	| FullWidthImageSlice
	| LatestArticlesSlice
	| RichTextSlice;

/**
 * Content for Post documents
 */
interface PostDocumentData {
	/**
	 * Title field in *Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Excerpt field in *Post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.excerpt
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	excerpt: prismic.RichTextField;

	/**
	 * Featured Image field in *Post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * ShowBackground field in *Post*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: post.showbackground
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	showbackground: prismic.BooleanField;

	/**
	 * Authors field in *Post*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.authors[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	authors: prismic.GroupField<Simplify<PostDocumentDataAuthorsItem>>;

	/**
	 * Categories field in *Post*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.categories[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	categories: prismic.GroupField<Simplify<PostDocumentDataCategoriesItem>>;

	/**
	 * Slice Zone field in *Post*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PostDocumentDataSlicesSlice> /**
	 * Meta Title field in *Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: post.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: post.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PostDocumentData>,
	'post',
	Lang
>;

/**
 * Item in *Publications → Authors*
 */
export interface PublicationsDocumentDataAuthorsItem {
	/**
	 * Author field in *Publications → Authors*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: publications.authors[].author
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	author: prismic.ContentRelationshipField<'people'>;
}

/**
 * Item in *Publications → Categories*
 */
export interface PublicationsDocumentDataCategoriesItem {
	/**
	 * Category field in *Publications → Categories*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: publications.categories[].category
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	category: prismic.ContentRelationshipField<'categories'>;
}

type PublicationsDocumentDataSlicesSlice = MediaEmbedSlice;

/**
 * Content for Publications documents
 */
interface PublicationsDocumentData {
	/**
	 * Title field in *Publications*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: publications.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Publication Image field in *Publications*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: publications.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Set publication image as background field in *Publications*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: publications.showbackground
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	showbackground: prismic.BooleanField;

	/**
	 * Authors field in *Publications*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: publications.authors[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	authors: prismic.GroupField<Simplify<PublicationsDocumentDataAuthorsItem>>;

	/**
	 * Categories field in *Publications*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: publications.categories[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	categories: prismic.GroupField<Simplify<PublicationsDocumentDataCategoriesItem>>;

	/**
	 * Body field in *Publications*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: publications.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Slice Zone field in *Publications*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: publications.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PublicationsDocumentDataSlicesSlice> /**
	 * Meta Title field in *Publications*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: publications.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Publications*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: publications.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Publications*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: publications.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Publications document from Prismic
 *
 * - **API ID**: `publications`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PublicationsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PublicationsDocumentData>,
	'publications',
	Lang
>;

type SearchDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Search documents
 */
interface SearchDocumentData {
	/**
	 * Title field in *Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: search.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Search*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: search.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Slice Zone field in *Search*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: search.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SearchDocumentDataSlicesSlice> /**
	 * Meta Title field in *Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: search.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: search.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Search*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: search.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Search document from Prismic
 *
 * - **API ID**: `search`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SearchDocumentData>,
	'search',
	Lang
>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
	/**
	 * Link field in *Settings → Navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Label field in *Settings → Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * CTA Button field in *Settings → Navigation*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: settings.navigation[].cta_button
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	cta_button: prismic.BooleanField;
}

/**
 * Item in *Settings → Footer Navigation*
 */
export interface SettingsDocumentDataFooterNavigationItem {
	/**
	 * Link field in *Settings → Footer Navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.footer_navigation[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Label field in *Settings → Footer Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.footer_navigation[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;
}

/**
 * Item in *Settings → Metadata for archive pages*
 */
export interface SettingsDocumentDataCustomTypeMetaItem {
	/**
	 * Content type field in *Settings → Metadata for archive pages*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.custom_type_meta[].content_type
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	content_type: prismic.SelectField<'Post' | 'Case Study' | 'Publications'>;

	/**
	 * Title field in *Settings → Metadata for archive pages*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.custom_type_meta[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Settings → Metadata for archive pages*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.custom_type_meta[].description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * Navigation field in *Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[]
	 * - **Tab**: Main Navigation
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>> /**
	 * Footer Navigation field in *Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.footer_navigation[]
	 * - **Tab**: Footer Navigation
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */;
	footer_navigation: prismic.GroupField<Simplify<SettingsDocumentDataFooterNavigationItem>> /**
	 * Site title field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.site_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	site_title: prismic.KeyTextField;

	/**
	 * Site description field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Open Graph Image field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.og_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>;

	/**
	 * Metadata for archive pages field in *Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.custom_type_meta[]
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	custom_type_meta: prismic.GroupField<Simplify<SettingsDocumentDataCustomTypeMetaItem>> /**
	 * Theme field in *Settings*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: default
	 * - **API ID Path**: settings.theme
	 * - **Tab**: Appearance
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */;
	theme: prismic.SelectField<'default' | 'fire' | 'ice' | 'autumn', 'filled'>;

	/**
	 * Latest Articles field in *Settings*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: Max content items to show in the 'Latest articles' block
	 * - **API ID Path**: settings.latest_articles
	 * - **Tab**: Appearance
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	latest_articles: prismic.NumberField /**
	 * Logo field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.logo
	 * - **Tab**: Logo
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */;
	logo: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

type TeamDocumentDataSlicesSlice = StaffSlice | RichTextSlice;

/**
 * Content for Team documents
 */
interface TeamDocumentData {
	/**
	 * Title field in *Team*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Slice Zone field in *Team*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<TeamDocumentDataSlicesSlice> /**
	 * Meta Title field in *Team*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: team.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Team*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: team.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Team*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Team document from Prismic
 *
 * - **API ID**: `team`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<TeamDocumentData>,
	'team',
	Lang
>;

export type AllDocumentTypes =
	| ArticleCategoriesDocument
	| CaseStudyDocument
	| CategoriesDocument
	| HomepageDocument
	| PageDocument
	| PeopleDocument
	| PostDocument
	| PublicationsDocument
	| SearchDocument
	| SettingsDocument
	| TeamDocument;

/**
 * Item in *Carousel → Default → Primary → Slide*
 */
export interface CarouselSliceDefaultPrimarySlideItem {
	/**
	 * Image field in *Carousel → Default → Primary → Slide*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: carousel.default.primary.slide[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Caption field in *Carousel → Default → Primary → Slide*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: carousel.default.primary.slide[].caption
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	caption: prismic.KeyTextField;
}

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
	/**
	 * Title field in *Carousel → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: carousel.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Carousel → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: carousel.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Slide field in *Carousel → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: carousel.default.primary.slide[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	slide: prismic.GroupField<Simplify<CarouselSliceDefaultPrimarySlideItem>>;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CarouselSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<'carousel', CarouselSliceVariation>;

/**
 * Item in *CaseStudies → Default → Primary → Case Studies*
 */
export interface CaseStudiesSliceDefaultPrimaryCaseStudiesItem {
	/**
	 * Case Study field in *CaseStudies → Default → Primary → Case Studies*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_studies.default.primary.case_studies[].case_study
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	case_study: prismic.ContentRelationshipField<'case_study'>;
}

/**
 * Item in *CaseStudies → Dark → Primary → Case Studies*
 */
export interface CaseStudiesSliceDarkPrimaryCaseStudiesItem {
	/**
	 * Case Study field in *CaseStudies → Dark → Primary → Case Studies*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_studies.dark.primary.case_studies[].case_study
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	case_study: prismic.ContentRelationshipField<'case_study'>;
}

/**
 * Primary content in *CaseStudies → Default → Primary*
 */
export interface CaseStudiesSliceDefaultPrimary {
	/**
	 * Heading field in *CaseStudies → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_studies.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Body field in *CaseStudies → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_studies.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Case Studies field in *CaseStudies → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_studies.default.primary.case_studies[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	case_studies: prismic.GroupField<Simplify<CaseStudiesSliceDefaultPrimaryCaseStudiesItem>>;
}

/**
 * Default variation for CaseStudies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CaseStudiesSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *CaseStudies → Dark → Primary*
 */
export interface CaseStudiesSliceDarkPrimary {
	/**
	 * Heading field in *CaseStudies → Dark → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_studies.dark.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Body field in *CaseStudies → Dark → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_studies.dark.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Case Studies field in *CaseStudies → Dark → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_studies.dark.primary.case_studies[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	case_studies: prismic.GroupField<Simplify<CaseStudiesSliceDarkPrimaryCaseStudiesItem>>;

	/**
	 * Top margin field in *CaseStudies → Dark → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: case_studies.dark.primary.top_margin
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	top_margin: prismic.BooleanField;
}

/**
 * Dark variation for CaseStudies Slice
 *
 * - **API ID**: `dark`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesSliceDark = prismic.SharedSliceVariation<
	'dark',
	Simplify<CaseStudiesSliceDarkPrimary>,
	never
>;

/**
 * Slice variation for *CaseStudies*
 */
type CaseStudiesSliceVariation = CaseStudiesSliceDefault | CaseStudiesSliceDark;

/**
 * CaseStudies Shared Slice
 *
 * - **API ID**: `case_studies`
 * - **Description**: CaseStudies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesSlice = prismic.SharedSlice<'case_studies', CaseStudiesSliceVariation>;

/**
 * Item in *DetailsCard → Default → Primary → Text*
 */
export interface DetailsCardSliceDefaultPrimaryTextItem {
	/**
	 * Title field in *DetailsCard → Default → Primary → Text*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: details_card.default.primary.text[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *DetailsCard → Default → Primary → Text*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: details_card.default.primary.text[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Item in *DetailsCard → Alternate Background → Primary → Text*
 */
export interface DetailsCardSliceAlternatePrimaryTextItem {
	/**
	 * Title field in *DetailsCard → Alternate Background → Primary → Text*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: details_card.alternate.primary.text[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *DetailsCard → Alternate Background → Primary → Text*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: details_card.alternate.primary.text[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *DetailsCard → Default → Primary*
 */
export interface DetailsCardSliceDefaultPrimary {
	/**
	 * Heading field in *DetailsCard → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: details_card.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Image field in *DetailsCard → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: details_card.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Text field in *DetailsCard → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: details_card.default.primary.text[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	text: prismic.GroupField<Simplify<DetailsCardSliceDefaultPrimaryTextItem>>;
}

/**
 * Default variation for DetailsCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailsCardSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<DetailsCardSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *DetailsCard → Alternate Background → Primary*
 */
export interface DetailsCardSliceAlternatePrimary {
	/**
	 * Heading field in *DetailsCard → Alternate Background → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: details_card.alternate.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Image field in *DetailsCard → Alternate Background → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: details_card.alternate.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Alternate Background field in *DetailsCard → Alternate Background → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: details_card.alternate.primary.alternate_background
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	alternate_background: prismic.BooleanField;

	/**
	 * Text field in *DetailsCard → Alternate Background → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: details_card.alternate.primary.text[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	text: prismic.GroupField<Simplify<DetailsCardSliceAlternatePrimaryTextItem>>;
}

/**
 * Alternate Background variation for DetailsCard Slice
 *
 * - **API ID**: `alternate`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailsCardSliceAlternate = prismic.SharedSliceVariation<
	'alternate',
	Simplify<DetailsCardSliceAlternatePrimary>,
	never
>;

/**
 * Slice variation for *DetailsCard*
 */
type DetailsCardSliceVariation = DetailsCardSliceDefault | DetailsCardSliceAlternate;

/**
 * DetailsCard Shared Slice
 *
 * - **API ID**: `details_card`
 * - **Description**: DetailsCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailsCardSlice = prismic.SharedSlice<'details_card', DetailsCardSliceVariation>;

/**
 * Item in *DiscoverCategories → Default → Primary → Categories*
 */
export interface DiscoverCategoriesSliceDefaultPrimaryCategoriesItem {
	/**
	 * Category field in *DiscoverCategories → Default → Primary → Categories*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: discover_categories.default.primary.categories[].category
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	category: prismic.ContentRelationshipField<'categories'>;

	/**
	 * Wide field in *DiscoverCategories → Default → Primary → Categories*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: discover_categories.default.primary.categories[].wide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	wide: prismic.BooleanField;
}

/**
 * Primary content in *DiscoverCategories → Default → Primary*
 */
export interface DiscoverCategoriesSliceDefaultPrimary {
	/**
	 * Heading field in *DiscoverCategories → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: discover_categories.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Categories field in *DiscoverCategories → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: discover_categories.default.primary.categories[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	categories: prismic.GroupField<Simplify<DiscoverCategoriesSliceDefaultPrimaryCategoriesItem>>;
}

/**
 * Default variation for DiscoverCategories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscoverCategoriesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<DiscoverCategoriesSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *DiscoverCategories*
 */
type DiscoverCategoriesSliceVariation = DiscoverCategoriesSliceDefault;

/**
 * DiscoverCategories Shared Slice
 *
 * - **API ID**: `discover_categories`
 * - **Description**: DiscoverCategories
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscoverCategoriesSlice = prismic.SharedSlice<
	'discover_categories',
	DiscoverCategoriesSliceVariation
>;

/**
 * Item in *Faqs → Default → Primary → FAQ*
 */
export interface FaqsSliceDefaultPrimaryFaqItem {
	/**
	 * Title field in *Faqs → Default → Primary → FAQ*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faqs.default.primary.faq[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Summary field in *Faqs → Default → Primary → FAQ*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faqs.default.primary.faq[].summary
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	summary: prismic.RichTextField;
}

/**
 * Item in *Faqs → Plain → Primary → FAQ*
 */
export interface FaqsSlicePlainPrimaryFaqItem {
	/**
	 * Title field in *Faqs → Plain → Primary → FAQ*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faqs.plain.primary.faq[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Summary field in *Faqs → Plain → Primary → FAQ*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faqs.plain.primary.faq[].summary
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	summary: prismic.RichTextField;
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
	/**
	 * Title field in *Faqs → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faqs.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Faqs → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faqs.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * FAQ field in *Faqs → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faqs.default.primary.faq[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	faq: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryFaqItem>>;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FaqsSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Faqs → Plain → Primary*
 */
export interface FaqsSlicePlainPrimary {
	/**
	 * Title field in *Faqs → Plain → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faqs.plain.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Faqs → Plain → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faqs.plain.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * FAQ field in *Faqs → Plain → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faqs.plain.primary.faq[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	faq: prismic.GroupField<Simplify<FaqsSlicePlainPrimaryFaqItem>>;
}

/**
 * Plain variation for Faqs Slice
 *
 * - **API ID**: `plain`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlicePlain = prismic.SharedSliceVariation<
	'plain',
	Simplify<FaqsSlicePlainPrimary>,
	never
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault | FaqsSlicePlain;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<'faqs', FaqsSliceVariation>;

/**
 * Item in *Footnotes → Default → Primary → Note*
 */
export interface FootnotesSliceDefaultPrimaryNoteItem {
	/**
	 * Body field in *Footnotes → Default → Primary → Note*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Add your footnote content here. It can contain links, italic and bold.
	 * - **API ID Path**: footnotes.default.primary.note[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Primary content in *Footnotes → Default → Primary*
 */
export interface FootnotesSliceDefaultPrimary {
	/**
	 * Note field in *Footnotes → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footnotes.default.primary.note[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	note: prismic.GroupField<Simplify<FootnotesSliceDefaultPrimaryNoteItem>>;
}

/**
 * Default variation for Footnotes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FootnotesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FootnotesSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Footnotes*
 */
type FootnotesSliceVariation = FootnotesSliceDefault;

/**
 * Footnotes Shared Slice
 *
 * - **API ID**: `footnotes`
 * - **Description**: Footnotes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FootnotesSlice = prismic.SharedSlice<'footnotes', FootnotesSliceVariation>;

/**
 * Primary content in *Form → Default → Primary*
 */
export interface FormSliceDefaultPrimary {
	/**
	 * Title field in *Form → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Form → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FormSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSlice = prismic.SharedSlice<'form', FormSliceVariation>;

/**
 * Primary content in *FullWidthImage → Default → Primary*
 */
export interface FullWidthImageSliceDefaultPrimary {
	/**
	 * Image field in *FullWidthImage → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_width_image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Caption field in *FullWidthImage → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_width_image.default.primary.caption
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	caption: prismic.KeyTextField;
}

/**
 * Default variation for FullWidthImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FullWidthImageSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FullWidthImage*
 */
type FullWidthImageSliceVariation = FullWidthImageSliceDefault;

/**
 * FullWidthImage Shared Slice
 *
 * - **API ID**: `full_width_image`
 * - **Description**: FullWidthImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthImageSlice = prismic.SharedSlice<
	'full_width_image',
	FullWidthImageSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Heading field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Body field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Button Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;

	/**
	 * Button Label field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.button_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_label: prismic.KeyTextField;

	/**
	 * Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Hero → Alternative → Primary*
 */
export interface HeroSliceAlternativePrimary {
	/**
	 * Heading field in *Hero → Alternative → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.alternative.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Body field in *Hero → Alternative → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.alternative.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Button Link field in *Hero → Alternative → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.alternative.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;

	/**
	 * Button Label field in *Hero → Alternative → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.alternative.primary.button_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_label: prismic.KeyTextField;

	/**
	 * Image field in *Hero → Alternative → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.alternative.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Alternative variation for Hero Slice
 *
 * - **API ID**: `alternative`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceAlternative = prismic.SharedSliceVariation<
	'alternative',
	Simplify<HeroSliceAlternativePrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceAlternative;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Item in *HorizontalGallery → Default → Primary → Gallery Image*
 */
export interface HorizontalGallerySliceDefaultPrimaryImageItem {
	/**
	 * Image field in *HorizontalGallery → Default → Primary → Gallery Image*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: horizontal_gallery.default.primary.image[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Caption field in *HorizontalGallery → Default → Primary → Gallery Image*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: horizontal_gallery.default.primary.image[].caption
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	caption: prismic.KeyTextField;
}

/**
 * Primary content in *HorizontalGallery → Default → Primary*
 */
export interface HorizontalGallerySliceDefaultPrimary {
	/**
	 * Title field in *HorizontalGallery → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: horizontal_gallery.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *HorizontalGallery → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: horizontal_gallery.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * Add background field in *HorizontalGallery → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: horizontal_gallery.default.primary.background
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	background: prismic.BooleanField;

	/**
	 * Gallery Image field in *HorizontalGallery → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: horizontal_gallery.default.primary.image[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	image: prismic.GroupField<Simplify<HorizontalGallerySliceDefaultPrimaryImageItem>>;
}

/**
 * Default variation for HorizontalGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HorizontalGallerySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HorizontalGallerySliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HorizontalGallery*
 */
type HorizontalGallerySliceVariation = HorizontalGallerySliceDefault;

/**
 * HorizontalGallery Shared Slice
 *
 * - **API ID**: `horizontal_gallery`
 * - **Description**: HorizontalGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HorizontalGallerySlice = prismic.SharedSlice<
	'horizontal_gallery',
	HorizontalGallerySliceVariation
>;

/**
 * Primary content in *LatestArticles → Default → Primary*
 */
export interface LatestArticlesSliceDefaultPrimary {
	/**
	 * Heading field in *LatestArticles → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: latest_articles.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Body field in *LatestArticles → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: latest_articles.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Default variation for LatestArticles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestArticlesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LatestArticlesSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *LatestArticles*
 */
type LatestArticlesSliceVariation = LatestArticlesSliceDefault;

/**
 * LatestArticles Shared Slice
 *
 * - **API ID**: `latest_articles`
 * - **Description**: LatestArticles
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestArticlesSlice = prismic.SharedSlice<
	'latest_articles',
	LatestArticlesSliceVariation
>;

/**
 * Item in *MasonryGallery → Default → Primary → Gallery Images*
 */
export interface MasonryGallerySliceDefaultPrimaryImagesItem {
	/**
	 * Image field in *MasonryGallery → Default → Primary → Gallery Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: masonry_gallery.default.primary.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Caption field in *MasonryGallery → Default → Primary → Gallery Images*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: masonry_gallery.default.primary.images[].caption
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	caption: prismic.KeyTextField;
}

/**
 * Primary content in *MasonryGallery → Default → Primary*
 */
export interface MasonryGallerySliceDefaultPrimary {
	/**
	 * Title field in *MasonryGallery → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: masonry_gallery.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *MasonryGallery → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: masonry_gallery.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * Gallery Images field in *MasonryGallery → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: masonry_gallery.default.primary.images[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<MasonryGallerySliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for MasonryGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MasonryGallerySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MasonryGallerySliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *MasonryGallery*
 */
type MasonryGallerySliceVariation = MasonryGallerySliceDefault;

/**
 * MasonryGallery Shared Slice
 *
 * - **API ID**: `masonry_gallery`
 * - **Description**: MasonryGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MasonryGallerySlice = prismic.SharedSlice<
	'masonry_gallery',
	MasonryGallerySliceVariation
>;

/**
 * Primary content in *MediaEmbed → Default → Primary*
 */
export interface MediaEmbedSliceDefaultPrimary {
	/**
	 * Title field in *MediaEmbed → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_embed.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *MediaEmbed → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_embed.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Link field in *MediaEmbed → Default → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: Embeds for Twitter do not work
	 * - **API ID Path**: media_embed.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	link: prismic.EmbedField;
}

/**
 * Default variation for MediaEmbed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaEmbedSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MediaEmbedSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *MediaEmbed → PrivacyEnhanced → Primary*
 */
export interface MediaEmbedSlicePrivacyEnhancedPrimary {
	/**
	 * Title field in *MediaEmbed → PrivacyEnhanced → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_embed.privacyEnhanced.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *MediaEmbed → PrivacyEnhanced → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_embed.privacyEnhanced.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Link field in *MediaEmbed → PrivacyEnhanced → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_embed.privacyEnhanced.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	link: prismic.EmbedField;
}

/**
 * PrivacyEnhanced variation for MediaEmbed Slice
 *
 * - **API ID**: `privacyEnhanced`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaEmbedSlicePrivacyEnhanced = prismic.SharedSliceVariation<
	'privacyEnhanced',
	Simplify<MediaEmbedSlicePrivacyEnhancedPrimary>,
	never
>;

/**
 * Slice variation for *MediaEmbed*
 */
type MediaEmbedSliceVariation = MediaEmbedSliceDefault | MediaEmbedSlicePrivacyEnhanced;

/**
 * MediaEmbed Shared Slice
 *
 * - **API ID**: `media_embed`
 * - **Description**: MediaEmbed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaEmbedSlice = prismic.SharedSlice<'media_embed', MediaEmbedSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Item in *Services → Default → Primary → Services*
 */
export interface ServicesSliceDefaultPrimaryServicesItem {
	/**
	 * Title field in *Services → Default → Primary → Services*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.services[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Services → Default → Primary → Services*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.services[].description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * Link field in *Services → Default → Primary → Services*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.services[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Link Text field in *Services → Default → Primary → Services*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.services[].linkText
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	linkText: prismic.KeyTextField;

	/**
	 * Icon field in *Services → Default → Primary → Services*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: arrow
	 * - **API ID Path**: services.default.primary.services[].icon
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	icon: prismic.SelectField<
		'arrow' | 'aperture' | 'bell' | 'calendar' | 'cycle' | 'gear',
		'filled'
	>;

	/**
	 * Style field in *Services → Default → Primary → Services*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: brand
	 * - **API ID Path**: services.default.primary.services[].style
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	style: prismic.SelectField<'brand' | 'accent' | 'highlight', 'filled'>;
}

/**
 * Item in *Services → Light → Primary → Services*
 */
export interface ServicesSliceLightPrimaryServicesItem {
	/**
	 * Title field in *Services → Light → Primary → Services*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.light.primary.services[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Services → Light → Primary → Services*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.light.primary.services[].description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * Link field in *Services → Light → Primary → Services*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.light.primary.services[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Link Text field in *Services → Light → Primary → Services*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.light.primary.services[].linkText
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	linkText: prismic.KeyTextField;

	/**
	 * Icon field in *Services → Light → Primary → Services*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: arrow
	 * - **API ID Path**: services.light.primary.services[].icon
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	icon: prismic.SelectField<
		'arrow' | 'aperture' | 'bell' | 'calendar' | 'cycle' | 'gear',
		'filled'
	>;

	/**
	 * Style field in *Services → Light → Primary → Services*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: brand
	 * - **API ID Path**: services.light.primary.services[].style
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	style: prismic.SelectField<'brand' | 'accent' | 'highlight', 'filled'>;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
	/**
	 * Heading field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Description field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * Services field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.services[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	services: prismic.GroupField<Simplify<ServicesSliceDefaultPrimaryServicesItem>>;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ServicesSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Services → Light → Primary*
 */
export interface ServicesSliceLightPrimary {
	/**
	 * Heading field in *Services → Light → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.light.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Description field in *Services → Light → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.light.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * Services field in *Services → Light → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.light.primary.services[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	services: prismic.GroupField<Simplify<ServicesSliceLightPrimaryServicesItem>>;
}

/**
 * Light variation for Services Slice
 *
 * - **API ID**: `light`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceLight = prismic.SharedSliceVariation<
	'light',
	Simplify<ServicesSliceLightPrimary>,
	never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault | ServicesSliceLight;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<'services', ServicesSliceVariation>;

/**
 * Primary content in *Showcase → Default → Primary*
 */
export interface ShowcaseSliceDefaultPrimary {
	/**
	 * Heading field in *Showcase → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Image field in *Showcase → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Icon field in *Showcase → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.icon
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	icon: prismic.SelectField<'gear' | 'cycle'>;

	/**
	 * Sub-heading field in *Showcase → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subheading: prismic.KeyTextField;

	/**
	 * Body field in *Showcase → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Button Link field in *Showcase → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;

	/**
	 * Button Text field in *Showcase → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;
}

/**
 * Default variation for Showcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowcaseSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ShowcaseSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Showcase → Reverse → Primary*
 */
export interface ShowcaseSliceReversePrimary {
	/**
	 * Heading field in *Showcase → Reverse → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.reverse.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Image field in *Showcase → Reverse → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.reverse.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Icon field in *Showcase → Reverse → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.reverse.primary.icon
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	icon: prismic.SelectField<'gear' | 'cycle'>;

	/**
	 * Sub-heading field in *Showcase → Reverse → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.reverse.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subheading: prismic.KeyTextField;

	/**
	 * Body field in *Showcase → Reverse → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.reverse.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Button Link field in *Showcase → Reverse → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.reverse.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;

	/**
	 * Button Text field in *Showcase → Reverse → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.reverse.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;
}

/**
 * Reverse variation for Showcase Slice
 *
 * - **API ID**: `reverse`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowcaseSliceReverse = prismic.SharedSliceVariation<
	'reverse',
	Simplify<ShowcaseSliceReversePrimary>,
	never
>;

/**
 * Slice variation for *Showcase*
 */
type ShowcaseSliceVariation = ShowcaseSliceDefault | ShowcaseSliceReverse;

/**
 * Showcase Shared Slice
 *
 * - **API ID**: `showcase`
 * - **Description**: Showcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowcaseSlice = prismic.SharedSlice<'showcase', ShowcaseSliceVariation>;

/**
 * Item in *Staff → Default → Primary → Staff Members*
 */
export interface StaffSliceDefaultPrimaryStaffMembersItem {
	/**
	 * Person field in *Staff → Default → Primary → Staff Members*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.default.primary.staff_members[].person
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	person: prismic.ContentRelationshipField<'people'>;
}

/**
 * Primary content in *Staff → Default → Primary*
 */
export interface StaffSliceDefaultPrimary {
	/**
	 * Title field in *Staff → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Staff Members field in *Staff → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.default.primary.staff_members[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	staff_members: prismic.GroupField<Simplify<StaffSliceDefaultPrimaryStaffMembersItem>>;
}

/**
 * Default variation for Staff Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaffSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<StaffSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Staff*
 */
type StaffSliceVariation = StaffSliceDefault;

/**
 * Staff Shared Slice
 *
 * - **API ID**: `staff`
 * - **Description**: Staff
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaffSlice = prismic.SharedSlice<'staff', StaffSliceVariation>;

/**
 * Item in *Tabs → Default → Primary → Tabs*
 */
export interface TabsSliceDefaultPrimaryTabsItem {
	/**
	 * Title field in *Tabs → Default → Primary → Tabs*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.default.primary.tabs[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Tabs → Default → Primary → Tabs*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.default.primary.tabs[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Link field in *Tabs → Default → Primary → Tabs*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.default.primary.tabs[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *Tabs → Default → Primary*
 */
export interface TabsSliceDefaultPrimary {
	/**
	 * Title field in *Tabs → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Tabs → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Tabs field in *Tabs → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.default.primary.tabs[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	tabs: prismic.GroupField<Simplify<TabsSliceDefaultPrimaryTabsItem>>;
}

/**
 * Default variation for Tabs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TabsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TabsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Tabs*
 */
type TabsSliceVariation = TabsSliceDefault;

/**
 * Tabs Shared Slice
 *
 * - **API ID**: `tabs`
 * - **Description**: Tabs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TabsSlice = prismic.SharedSlice<'tabs', TabsSliceVariation>;

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
	/**
	 * Section heading field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Section description field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * Testimonial text field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;

	/**
	 * Citation field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.citation
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	citation: prismic.KeyTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TestimonialsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<'testimonials', TestimonialsSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			ArticleCategoriesDocument,
			ArticleCategoriesDocumentData,
			CaseStudyDocument,
			CaseStudyDocumentData,
			CaseStudyDocumentDataAuthorsItem,
			CaseStudyDocumentDataSlicesSlice,
			CategoriesDocument,
			CategoriesDocumentData,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			PeopleDocument,
			PeopleDocumentData,
			PeopleDocumentDataSlicesSlice,
			PeopleDocumentDataPlatformItem,
			PostDocument,
			PostDocumentData,
			PostDocumentDataAuthorsItem,
			PostDocumentDataCategoriesItem,
			PostDocumentDataSlicesSlice,
			PublicationsDocument,
			PublicationsDocumentData,
			PublicationsDocumentDataAuthorsItem,
			PublicationsDocumentDataCategoriesItem,
			PublicationsDocumentDataSlicesSlice,
			SearchDocument,
			SearchDocumentData,
			SearchDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataNavigationItem,
			SettingsDocumentDataFooterNavigationItem,
			SettingsDocumentDataCustomTypeMetaItem,
			TeamDocument,
			TeamDocumentData,
			TeamDocumentDataSlicesSlice,
			AllDocumentTypes,
			CarouselSlice,
			CarouselSliceDefaultPrimarySlideItem,
			CarouselSliceDefaultPrimary,
			CarouselSliceVariation,
			CarouselSliceDefault,
			CaseStudiesSlice,
			CaseStudiesSliceDefaultPrimaryCaseStudiesItem,
			CaseStudiesSliceDefaultPrimary,
			CaseStudiesSliceDarkPrimaryCaseStudiesItem,
			CaseStudiesSliceDarkPrimary,
			CaseStudiesSliceVariation,
			CaseStudiesSliceDefault,
			CaseStudiesSliceDark,
			DetailsCardSlice,
			DetailsCardSliceDefaultPrimaryTextItem,
			DetailsCardSliceDefaultPrimary,
			DetailsCardSliceAlternatePrimaryTextItem,
			DetailsCardSliceAlternatePrimary,
			DetailsCardSliceVariation,
			DetailsCardSliceDefault,
			DetailsCardSliceAlternate,
			DiscoverCategoriesSlice,
			DiscoverCategoriesSliceDefaultPrimaryCategoriesItem,
			DiscoverCategoriesSliceDefaultPrimary,
			DiscoverCategoriesSliceVariation,
			DiscoverCategoriesSliceDefault,
			FaqsSlice,
			FaqsSliceDefaultPrimaryFaqItem,
			FaqsSliceDefaultPrimary,
			FaqsSlicePlainPrimaryFaqItem,
			FaqsSlicePlainPrimary,
			FaqsSliceVariation,
			FaqsSliceDefault,
			FaqsSlicePlain,
			FootnotesSlice,
			FootnotesSliceDefaultPrimaryNoteItem,
			FootnotesSliceDefaultPrimary,
			FootnotesSliceVariation,
			FootnotesSliceDefault,
			FormSlice,
			FormSliceDefaultPrimary,
			FormSliceVariation,
			FormSliceDefault,
			FullWidthImageSlice,
			FullWidthImageSliceDefaultPrimary,
			FullWidthImageSliceVariation,
			FullWidthImageSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceAlternativePrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroSliceAlternative,
			HorizontalGallerySlice,
			HorizontalGallerySliceDefaultPrimaryImageItem,
			HorizontalGallerySliceDefaultPrimary,
			HorizontalGallerySliceVariation,
			HorizontalGallerySliceDefault,
			LatestArticlesSlice,
			LatestArticlesSliceDefaultPrimary,
			LatestArticlesSliceVariation,
			LatestArticlesSliceDefault,
			MasonryGallerySlice,
			MasonryGallerySliceDefaultPrimaryImagesItem,
			MasonryGallerySliceDefaultPrimary,
			MasonryGallerySliceVariation,
			MasonryGallerySliceDefault,
			MediaEmbedSlice,
			MediaEmbedSliceDefaultPrimary,
			MediaEmbedSlicePrivacyEnhancedPrimary,
			MediaEmbedSliceVariation,
			MediaEmbedSliceDefault,
			MediaEmbedSlicePrivacyEnhanced,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			ServicesSlice,
			ServicesSliceDefaultPrimaryServicesItem,
			ServicesSliceDefaultPrimary,
			ServicesSliceLightPrimaryServicesItem,
			ServicesSliceLightPrimary,
			ServicesSliceVariation,
			ServicesSliceDefault,
			ServicesSliceLight,
			ShowcaseSlice,
			ShowcaseSliceDefaultPrimary,
			ShowcaseSliceReversePrimary,
			ShowcaseSliceVariation,
			ShowcaseSliceDefault,
			ShowcaseSliceReverse,
			StaffSlice,
			StaffSliceDefaultPrimaryStaffMembersItem,
			StaffSliceDefaultPrimary,
			StaffSliceVariation,
			StaffSliceDefault,
			TabsSlice,
			TabsSliceDefaultPrimaryTabsItem,
			TabsSliceDefaultPrimary,
			TabsSliceVariation,
			TabsSliceDefault,
			TestimonialsSlice,
			TestimonialsSliceDefaultPrimary,
			TestimonialsSliceVariation,
			TestimonialsSliceDefault
		};
	}
}
